// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MundoVs.Infrastructure.Data;

#nullable disable

namespace MundoVs.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260221071743_AgregarRelacionTiposProceso")]
    partial class AgregarRelacionTiposProceso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.Horma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Medidas")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Talla");

                    b.ToTable("Hormas");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.ProductoCalzado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Temporada")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoSuela")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosCalzado");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.TallaCalzado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductoCalzadoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TallaEU")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TallaUK")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TallaUS")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductoCalzadoId");

                    b.ToTable("TallasCalzado");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Industria")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RfcCif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("RfcCif");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Movil")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPedido");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.PedidoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Especificaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Industria")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Industria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.ColorSerigrafia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoHex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("CodigoPantone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductoSerigrafiaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductoSerigrafiaId");

                    b.ToTable("ColoresSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.CotizacionSerigrafia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CostoCentradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoLavadoPantalla")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoRecogidoAmarrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoSerigrafista1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoSerigrafista2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTiradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalPorPar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalPorTarea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Ganancia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastoAdministracion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastoElectricidadPlancha")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastoElectricidadPulpo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastoLuzGeneral")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastosFijos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InsumoCiclo1RACantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoCiclo1RACosto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoCiclo1RAPrecio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoCicloEcoCantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoCicloEcoCosto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoCicloEcoPrecio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoDrySiliconCantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoDrySiliconCosto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoDrySiliconPrecio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoPTWaxCantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoPTWaxCosto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoPTWaxPrecio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoTrapoBlancoCantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoTrapoBlancoCosto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoTrapoBlancoPrecio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoX6Cantidad")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoX6Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("InsumoX6Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParesPorLamina")
                        .HasColumnType("int");

                    b.Property<Guid>("PedidoSerigrafiaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecioCentradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioFinalContado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLavadoPantalla")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioRecogidoAmarrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSerigrafista1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSerigrafista2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSugerido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioTiradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoCentradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoLavadoPantalla")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoRecogidoAmarrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoSerigrafista1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoSerigrafista2")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoTiradoMaterial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tinta1Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta1Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta1Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta1PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta1PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta1PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta2Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta2Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta2Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta2PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta2PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta2PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta3Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta3Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta3Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta3PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta3PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta3PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta4Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta4Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta4Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta4PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta4PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta4PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta5Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta5Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta5Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta5PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta5PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta5PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta6Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta6Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta6Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta6PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta6PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta6PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta7Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta7Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta7Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta7PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta7PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta7PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta8Consumo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta8Costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tinta8Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Tinta8PesoFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta8PesoInicial")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Tinta8PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Utilidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoSerigrafiaId");

                    b.ToTable("CotizacionesSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.Diseno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprobado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Dimensiones")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumeroColores")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Disenos");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.EscalaSerigrafia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Talla15")
                        .HasColumnType("int");

                    b.Property<int>("Talla16")
                        .HasColumnType("int");

                    b.Property<int>("Talla17")
                        .HasColumnType("int");

                    b.Property<int>("Talla18")
                        .HasColumnType("int");

                    b.Property<int>("Talla19")
                        .HasColumnType("int");

                    b.Property<int>("Talla20")
                        .HasColumnType("int");

                    b.Property<int>("Talla21")
                        .HasColumnType("int");

                    b.Property<int>("Talla22")
                        .HasColumnType("int");

                    b.Property<int>("Talla23")
                        .HasColumnType("int");

                    b.Property<int>("Talla24")
                        .HasColumnType("int");

                    b.Property<int>("Talla25")
                        .HasColumnType("int");

                    b.Property<int>("Talla26")
                        .HasColumnType("int");

                    b.Property<int>("Talla27")
                        .HasColumnType("int");

                    b.Property<int>("Talla28")
                        .HasColumnType("int");

                    b.Property<int>("Talla29")
                        .HasColumnType("int");

                    b.Property<int>("Talla30")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EscalasSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.Pantalla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Dimensiones")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DisenoPara")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MallaNumero")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UsosTotales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pantallas");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Combinacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Corrida")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRecibido")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Hecho")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoteCliente")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PedidoDetalleId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ProcesoFrecuencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoMesa")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoPlancha")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoPlastisol")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoPoteo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoPulpo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoSublimacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoTransfer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProcesoUV")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Talla15")
                        .HasColumnType("int");

                    b.Property<int?>("Talla16")
                        .HasColumnType("int");

                    b.Property<int?>("Talla17")
                        .HasColumnType("int");

                    b.Property<int?>("Talla18")
                        .HasColumnType("int");

                    b.Property<int?>("Talla19")
                        .HasColumnType("int");

                    b.Property<int?>("Talla20")
                        .HasColumnType("int");

                    b.Property<int?>("Talla21")
                        .HasColumnType("int");

                    b.Property<int?>("Talla22")
                        .HasColumnType("int");

                    b.Property<int?>("Talla23")
                        .HasColumnType("int");

                    b.Property<int?>("Talla24")
                        .HasColumnType("int");

                    b.Property<int?>("Talla25")
                        .HasColumnType("int");

                    b.Property<int?>("Talla26")
                        .HasColumnType("int");

                    b.Property<int?>("Talla27")
                        .HasColumnType("int");

                    b.Property<int?>("Talla28")
                        .HasColumnType("int");

                    b.Property<int?>("Talla29")
                        .HasColumnType("int");

                    b.Property<int?>("Talla30")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FechaEstimada");

                    b.HasIndex("Hecho");

                    b.HasIndex("PedidoDetalleId");

                    b.ToTable("PedidosSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafiaProcesoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PedidoSerigrafiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TipoProcesoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PedidoSerigrafiaId");

                    b.HasIndex("TipoProcesoId");

                    b.ToTable("PedidoSerigrafiaProcesoDetalles");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.ProductoSerigrafia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaterialBase")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroColores")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TamanoImpresion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoImpresion")
                        .HasColumnType("int");

                    b.Property<string>("TipoTinta")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.Tinta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoHex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("CodigoPantone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tintas");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.TipoProceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("CostoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre");

                    b.ToTable("TiposProceso");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.ProductoCalzado", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.TallaCalzado", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Calzado.ProductoCalzado", "ProductoCalzado")
                        .WithMany("Tallas")
                        .HasForeignKey("ProductoCalzadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoCalzado");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Contacto", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Cliente", "Cliente")
                        .WithMany("Contactos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Pedido", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MundoVs.Core.Entities.Producto", "Producto")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.ColorSerigrafia", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Serigrafia.ProductoSerigrafia", "ProductoSerigrafia")
                        .WithMany("Colores")
                        .HasForeignKey("ProductoSerigrafiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.CotizacionSerigrafia", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafia", "PedidoSerigrafia")
                        .WithMany()
                        .HasForeignKey("PedidoSerigrafiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoSerigrafia");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.Diseno", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafia", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.PedidoDetalle", "PedidoDetalle")
                        .WithMany()
                        .HasForeignKey("PedidoDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoDetalle");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafiaProcesoDetalle", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafia", "PedidoSerigrafia")
                        .WithMany("TiposProceso")
                        .HasForeignKey("PedidoSerigrafiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MundoVs.Core.Entities.Serigrafia.TipoProceso", "TipoProceso")
                        .WithMany("PedidosProcesos")
                        .HasForeignKey("TipoProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PedidoSerigrafia");

                    b.Navigation("TipoProceso");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.ProductoSerigrafia", b =>
                {
                    b.HasOne("MundoVs.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Calzado.ProductoCalzado", b =>
                {
                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Cliente", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Producto", b =>
                {
                    b.Navigation("PedidoDetalles");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.PedidoSerigrafia", b =>
                {
                    b.Navigation("TiposProceso");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.ProductoSerigrafia", b =>
                {
                    b.Navigation("Colores");
                });

            modelBuilder.Entity("MundoVs.Core.Entities.Serigrafia.TipoProceso", b =>
                {
                    b.Navigation("PedidosProcesos");
                });
#pragma warning restore 612, 618
        }
    }
}
